# Generated by Django 3.2.16 on 2022-12-13 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='../default_post_wdyur2', upload_to='images/')),
                ('image_filter', models.CharField(choices=[('none', 'None'), ('appetizer', 'Appetizer'), ('breakfast_&_brunch', 'Breakfast & Brunch'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('main_dish', 'Main Dish'), ('side_dish', 'Side Dish'), ('salad', 'Salad'), ('condiment', 'Condiemnt'), ('soup_&_stew', 'Soup & Stew'), ('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('legume', 'Legume'), ('grain', 'Grain'), ('meat', 'Meat'), ('poultry', 'Poultry'), ('fish', 'Fish'), ('seafood', 'Seafood'), ('egg', 'Egg'), ('mushroom', 'Mushroom'), ('cheese_&_dairy', 'Cheese & Dairy'), ('nuts_&_seeds', 'Nuts & Seeds'), ('herbs_&_spices', 'Herbs & Spices')], default='normal', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
