# Generated by Django 3.2.16 on 2022-12-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20221220_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='course',
            field=models.CharField(choices=[('none', 'None'), ('appetizers_&_snacks', 'Appetizers & Snacks'), ('breakfast_&_brunch', 'Breakfast & Brunch'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('desserts', 'Desserts'), ('main_dishes', 'Main Dishes'), ('side_dishes', 'Side Dishes'), ('salads', 'Salads'), ('condiments', 'Condiemnts'), ('soups_&_stews', 'Soups & Stews')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('none', 'None'), ('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('legumes', 'Legumes'), ('grains', 'Grains'), ('meats', 'Meats'), ('poultry', 'Poultry'), ('fish', 'Fish'), ('seafood', 'Seafood'), ('eggs', 'Eggs'), ('mushrooms', 'Mushrooms'), ('cheese_&_dairy', 'Cheese & Dairy'), ('nuts_&_seeds', 'Nuts & Seeds'), ('herbs_&_spices', 'Herbs & Spices')], default='none', max_length=20),
        ),
    ]
