# Generated by Django 3.2.16 on 2022-12-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='city',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='country',
        ),
    ]
