# Generated by Django 3.2.16 on 2022-12-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_published_date_book_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_wdyur2', upload_to='images/'),
        ),
    ]
