# Generated by Django 3.2.16 on 2022-12-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20221217_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_link',
            field=models.URLField(blank=True, max_length=400, verbose_name='Book URL'),
        ),
    ]
